version: '3.8'

services:
  ricu:
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/data/physionet.org/files/mimiciv/3.1/:/var/data/miiv
      - ~/data/physionet.org/files/eicu-crd/2.0/:/var/data/eicu
